# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf8ff10bfed76851128638ab7602fb60f00d4881bd413620899bc95c0fe69155863195270044b8a30ed7ef673daf8e42c00aaf127d805a0e233399466daae76b

test:
  secret_key_base: 0f70d30e82e9f7424a8f7d2fd2cf70df3497ba11e25471f9c6894800ec3a6374c2d8ae6f8f64970a5128a801f1dcbf382b1c3880235e2879f367e487f482b718

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
